#!/usr/bin/env python

# Show help for Python

__author__ = "Miki Tebeka <miki@mikitebeka.com>"
__license__ = "BSD"

def main(argv=None):
    import sys
    from optparse import OptionParser
    import webbrowser

    argv = argv or sys.argv

    parser = OptionParser("%prog [MODULE[.FUNCITON]]")
    opts, args = parser.parse_args(argv[1:])

    if len(args) not in (0, 1):
        parser.error("wrong number of arguments") # Will exit

    root = "http://docs.python.org"

    if not args:
        url = "%s/%s" % (root, "modindex.html")
    elif "." in args[0]:
        module, function = args[0].split(".")
        url = "%s/library/%s.html#%s.%s" % (root, module, module, function)
    else:
        url = "%s/library/%s.html" % (root, args[0])

    webbrowser.open(url)

if __name__ == "__main__":
    main()
