#!/bin/bash
# From http://www.cliki.net/rlwrap
# See above URL on how to generate ${HOME}/.sbcl_completions

BREAK_CHARS="(){}[],^%$#@\"\";''|\\"
rlwrap \
    --remember \
    --history-filename=${HOME}/.sbcl_history \
    --histsize=1000000 \
    -c \
    -b ${BREAK_CHARS} \
    -f ${HOME}/.sbcl_completions \
    /usr/bin/sbcl $@
