#!/bin/bash

start() {
    conf=lighttpd.conf
    sed -e "s=_PWD_=$PWD=" ${conf}.in > $conf
    lighttpd -f $conf
}

stop() {
    pidfile=lighttpd.pid
    if [ -f $pidfile ]; then
        kill `cat $pidfile` # lighttpd will delete the pid file
    fi
}

if [ $# -ne 1 ]; then
    echo "usage: `basename $0` start|stop|restart" 1>&2
    exit 1
fi

case $1 in
    start ) start;;
    stop ) stop;;
    restart ) stop; start;;
    * ) echo "error: unknown action - $1" 1>&2; exit 1;;
esac
