// Code generated by protoc-gen-go. DO NOT EDIT.
// source: job.proto

package pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Value struct {
	// Types that are valid to be assigned to Value:
	//	*Value_Int
	//	*Value_Str
	Value                isValue_Value `protobuf_oneof:"value"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *Value) Reset()         { *m = Value{} }
func (m *Value) String() string { return proto.CompactTextString(m) }
func (*Value) ProtoMessage()    {}
func (*Value) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{0}
}

func (m *Value) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Value.Unmarshal(m, b)
}
func (m *Value) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Value.Marshal(b, m, deterministic)
}
func (m *Value) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Value.Merge(m, src)
}
func (m *Value) XXX_Size() int {
	return xxx_messageInfo_Value.Size(m)
}
func (m *Value) XXX_DiscardUnknown() {
	xxx_messageInfo_Value.DiscardUnknown(m)
}

var xxx_messageInfo_Value proto.InternalMessageInfo

type isValue_Value interface {
	isValue_Value()
}

type Value_Int struct {
	Int int64 `protobuf:"varint,1,opt,name=int,proto3,oneof"`
}

type Value_Str struct {
	Str string `protobuf:"bytes,2,opt,name=str,proto3,oneof"`
}

func (*Value_Int) isValue_Value() {}

func (*Value_Str) isValue_Value() {}

func (m *Value) GetValue() isValue_Value {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *Value) GetInt() int64 {
	if x, ok := m.GetValue().(*Value_Int); ok {
		return x.Int
	}
	return 0
}

func (m *Value) GetStr() string {
	if x, ok := m.GetValue().(*Value_Str); ok {
		return x.Str
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*Value) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _Value_OneofMarshaler, _Value_OneofUnmarshaler, _Value_OneofSizer, []interface{}{
		(*Value_Int)(nil),
		(*Value_Str)(nil),
	}
}

func _Value_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Int:
		b.EncodeVarint(1<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Int))
	case *Value_Str:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Str)
	case nil:
	default:
		return fmt.Errorf("Value.Value has unexpected type %T", x)
	}
	return nil
}

func _Value_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*Value)
	switch tag {
	case 1: // value.int
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Value = &Value_Int{int64(x)}
		return true, err
	case 2: // value.str
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Value = &Value_Str{x}
		return true, err
	default:
		return false, nil
	}
}

func _Value_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*Value)
	// value
	switch x := m.Value.(type) {
	case *Value_Int:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(x.Int))
	case *Value_Str:
		n += 1 // tag and wire
		n += proto.SizeVarint(uint64(len(x.Str)))
		n += len(x.Str)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Job struct {
	User                 string            `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Count                int64             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Properties           map[string]*Value `protobuf:"bytes,3,rep,name=properties,proto3" json:"properties,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Job) Reset()         { *m = Job{} }
func (m *Job) String() string { return proto.CompactTextString(m) }
func (*Job) ProtoMessage()    {}
func (*Job) Descriptor() ([]byte, []int) {
	return fileDescriptor_f32c477d91a04ead, []int{1}
}

func (m *Job) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Job.Unmarshal(m, b)
}
func (m *Job) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Job.Marshal(b, m, deterministic)
}
func (m *Job) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Job.Merge(m, src)
}
func (m *Job) XXX_Size() int {
	return xxx_messageInfo_Job.Size(m)
}
func (m *Job) XXX_DiscardUnknown() {
	xxx_messageInfo_Job.DiscardUnknown(m)
}

var xxx_messageInfo_Job proto.InternalMessageInfo

func (m *Job) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

func (m *Job) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Job) GetProperties() map[string]*Value {
	if m != nil {
		return m.Properties
	}
	return nil
}

func init() {
	proto.RegisterType((*Value)(nil), "pb.Value")
	proto.RegisterType((*Job)(nil), "pb.Job")
	proto.RegisterMapType((map[string]*Value)(nil), "pb.Job.PropertiesEntry")
}

func init() { proto.RegisterFile("job.proto", fileDescriptor_f32c477d91a04ead) }

var fileDescriptor_f32c477d91a04ead = []byte{
	// 208 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x4f, 0x3d, 0x6b, 0xc3, 0x30,
	0x14, 0xac, 0xac, 0xba, 0x45, 0xcf, 0x43, 0xcb, 0xa3, 0x50, 0xd3, 0xa5, 0xc6, 0x93, 0x27, 0x0d,
	0xee, 0x50, 0x93, 0x31, 0x10, 0x30, 0x9e, 0x82, 0x86, 0xec, 0x51, 0xd0, 0xe0, 0x24, 0x58, 0x42,
	0x92, 0x03, 0xfe, 0x5b, 0xf9, 0x85, 0x41, 0xb2, 0x09, 0x21, 0xdb, 0x7d, 0xe8, 0x74, 0xef, 0x80,
	0x1d, 0xb5, 0xe4, 0xc6, 0x6a, 0xaf, 0x31, 0x31, 0xb2, 0x6c, 0x20, 0xdd, 0xed, 0xcf, 0xa3, 0x42,
	0x04, 0xda, 0x0f, 0x3e, 0x27, 0x05, 0xa9, 0x68, 0xfb, 0x22, 0x02, 0x09, 0x9a, 0xf3, 0x36, 0x4f,
	0x0a, 0x52, 0xb1, 0xa0, 0x39, 0x6f, 0xd7, 0xef, 0x90, 0x5e, 0x42, 0xa0, 0xbc, 0x12, 0xa0, 0x9d,
	0x96, 0x88, 0xf0, 0x3a, 0x3a, 0x65, 0x63, 0x92, 0x89, 0x88, 0xf1, 0x0b, 0xd2, 0x83, 0x1e, 0x07,
	0x1f, 0xa3, 0x54, 0xcc, 0x04, 0xff, 0x01, 0x8c, 0xd5, 0x46, 0x59, 0xdf, 0x2b, 0x97, 0xd3, 0x82,
	0x56, 0x59, 0xfd, 0xcd, 0x8d, 0xe4, 0x9d, 0x96, 0x7c, 0x7b, 0x77, 0x36, 0x83, 0xb7, 0x93, 0x78,
	0x78, 0xfa, 0xd3, 0xc2, 0xc7, 0x93, 0x8d, 0x9f, 0x40, 0x4f, 0x6a, 0x5a, 0x4a, 0x03, 0xc4, 0xdf,
	0xe5, 0xb0, 0xd8, 0x99, 0xd5, 0x2c, 0x7c, 0x1c, 0xa7, 0x89, 0x59, 0x5f, 0x25, 0x0d, 0x91, 0x6f,
	0x71, 0xf9, 0xdf, 0x2d, 0x00, 0x00, 0xff, 0xff, 0x43, 0x9e, 0x37, 0x9a, 0x06, 0x01, 0x00, 0x00,
}
